onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_bryant_rca_8b/OP_A
add wave -noupdate /tb_bryant_rca_8b/OP_B
add wave -noupdate /tb_bryant_rca_8b/CLK
add wave -noupdate -radix decimal /tb_bryant_rca_8b/reset
add wave -noupdate /tb_bryant_rca_8b/en
add wave -noupdate /tb_bryant_rca_8b/Sum_Q
add wave -noupdate /tb_bryant_rca_8b/Exp_Sum_Q
add wave -noupdate /tb_bryant_rca_8b/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/Exp_Carry_Q
add wave -noupdate /tb_bryant_rca_8b/Test_OutS
add wave -noupdate /tb_bryant_rca_8b/LineNumber
add wave -noupdate /tb_bryant_rca_8b/U0/CLK
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/clk
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/reset
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/en
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/s1
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/s2
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/s3
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/Rs1
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/Rs2
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/Rs3
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/c1
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/c2
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/c3
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/RAout1
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/RAout2
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/RAout3
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/RBout1
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/RBout2
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/RBout3
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/Rc1
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/Rc2
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/Rc3
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/s1
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/s2
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/s3
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/s4
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/s5
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/s6
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/s7
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/s8
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/c1
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/c2
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/c3
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/c4
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/c5
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/c6
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/c7
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/c8
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_First_BSlice1/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_First_BSlice1/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_First_BSlice1/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_First_BSlice1/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice3/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice3/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice3/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice3/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice3/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice4/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice4/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice4/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice4/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice4/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice5/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice5/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice5/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice5/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice5/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice6/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice6/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice6/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice6/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice6/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice7/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice7/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice7/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice7/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_First_8B/InstBRYANT_GEN_BSlice7/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG1/clk
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG1/reset
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG1/en
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG1/InA
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG1/InB
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG1/SumIn
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG1/CarryIn
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG1/Aout
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG1/Bout
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG1/SumOut
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG1/Carryout
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG1/sAout
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG1/sBout
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG1/sSumout
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG1/scarryout
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/s1
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/s2
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/s3
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/s4
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/s5
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/s6
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/s7
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/s8
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/c1
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/c2
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/c3
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/c4
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/c5
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/c6
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/c7
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/c8
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice3/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice3/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice3/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice3/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice3/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice4/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice4/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice4/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice4/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice4/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice5/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice5/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice5/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice5/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice5/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice6/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice6/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice6/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice6/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice6/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice7/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice7/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice7/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice7/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice7/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice8/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice8/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice8/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice8/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_8B1/InstBRYANT_GEN_BSlice8/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG2/clk
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG2/reset
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG2/en
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG2/InA
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG2/InB
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG2/SumIn
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG2/PrevSum
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG2/CarryIn
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG2/Aout
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG2/Bout
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG2/SumOut
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG2/Carryout
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG2/sAout
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG2/sBout
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG2/sSumout
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_REG2/scarryout
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/s1
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/s2
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/s3
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/s4
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/s5
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/s6
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/s7
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/s8
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/c1
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/c2
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/c3
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/c4
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/c5
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/c6
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/c7
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/c8
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice3/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice3/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice3/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice3/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice3/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice4/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice4/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice4/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice4/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice4/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice5/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice5/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice5/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice5/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice5/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice6/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice6/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice6/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice6/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice6/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice7/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice7/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice7/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice7/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice7/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice8/Op_A
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice8/Op_B
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice8/Op_C
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice8/SUM_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice8/Carry_Q
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_Last_REG1/clk
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_Last_REG1/reset
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_Last_REG1/en
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_Last_REG1/SumIn
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_Last_REG1/PrevSum
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_Last_REG1/CarryIn
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_Last_REG1/SumOut
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_Last_REG1/Carryout
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_Last_REG1/sSumout
add wave -noupdate /tb_bryant_rca_8b/InstBRYANT_RCA_8B/InstBRYANT_RCA_Last_REG1/scarryout
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 5} {0 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {1 us}
