onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix decimal /tb_bryant_rca_6b/OP_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/OP_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/CLK
add wave -noupdate -radix decimal /tb_bryant_rca_6b/reset
add wave -noupdate -radix decimal /tb_bryant_rca_6b/en
add wave -noupdate -radix decimal /tb_bryant_rca_6b/Exp_Sum_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/Exp_Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/Test_OutS
add wave -noupdate -radix decimal /tb_bryant_rca_6b/LineNumber
add wave -noupdate -radix decimal /tb_bryant_rca_6b/U0/CLK
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/clk
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/reset
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/en
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/s1
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/s2
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/s3
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/s4
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/Rs1
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/Rs2
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/Rs3
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/Rs4
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/c1
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/c2
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/c3
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/c4
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/RAout1
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/RAout2
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/RAout3
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/RAout4
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/RBout1
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/RBout2
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/RBout3
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/RBout4
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/Rc1
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/Rc2
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/Rc3
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/Rc4
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/s1
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/s2
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/s3
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/s4
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/s5
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/s6
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/c1
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/c2
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/c3
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/c4
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/c5
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/c6
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_First_BSlice1/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_First_BSlice1/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_First_BSlice1/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_First_BSlice1/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice3/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice3/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice3/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice3/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice3/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice4/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice4/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice4/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice4/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice4/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice5/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice5/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice5/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice5/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_First_6B/InstBRYANT_GEN_BSlice5/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG1/clk
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG1/reset
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG1/en
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG1/InA
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG1/InB
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG1/SumIn
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG1/CarryIn
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG1/Aout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG1/Bout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG1/SumOut
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG1/Carryout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG1/sAout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG1/sBout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG1/sSumout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG1/scarryout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/s1
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/s2
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/s3
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/s4
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/s5
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/s6
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/c1
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/c2
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/c3
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/c4
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/c5
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/c6
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice3/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice3/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice3/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice3/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice3/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice4/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice4/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice4/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice4/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice4/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice5/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice5/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice5/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice5/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice5/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice6/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice6/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice6/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice6/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B1/InstBRYANT_GEN_BSlice6/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG2/clk
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG2/reset
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG2/en
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG2/InA
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG2/InB
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG2/SumIn
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG2/PrevSum
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG2/CarryIn
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG2/Aout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG2/Bout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG2/SumOut
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG2/Carryout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG2/sAout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG2/sBout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG2/sSumout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG2/scarryout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/s1
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/s2
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/s3
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/s4
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/s5
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/s6
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/c1
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/c2
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/c3
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/c4
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/c5
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/c6
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice3/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice3/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice3/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice3/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice3/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice4/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice4/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice4/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice4/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice4/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice5/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice5/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice5/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice5/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice5/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice6/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice6/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice6/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice6/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B2/InstBRYANT_GEN_BSlice6/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG3/clk
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG3/reset
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG3/en
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG3/InA
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG3/InB
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG3/SumIn
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG3/PrevSum
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG3/CarryIn
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG3/Aout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG3/Bout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG3/SumOut
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG3/Carryout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG3/sAout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG3/sBout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG3/sSumout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_REG3/scarryout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/s1
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/s2
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/s3
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/s4
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/s5
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/s6
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/c1
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/c2
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/c3
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/c4
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/c5
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/c6
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice3/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice3/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice3/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice3/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice3/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice4/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice4/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice4/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice4/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice4/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice5/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice5/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice5/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice5/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice5/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice6/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice6/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice6/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice6/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_GEN_6B5/InstBRYANT_GEN_BSlice6/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_Last_REG1/clk
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_Last_REG1/reset
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_Last_REG1/en
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_Last_REG1/SumIn
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_Last_REG1/PrevSum
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_Last_REG1/CarryIn
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_Last_REG1/SumOut
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_Last_REG1/Carryout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_Last_REG1/sSumout
add wave -noupdate -radix decimal /tb_bryant_rca_6b/InstBRYANT_RCA_6B/InstBRYANT_RCA_Last_REG1/scarryout
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0} {{Cursor 2} {169 ns} 0} {{Cursor 3} {269 ns} 0}
quietly wave cursor active 3
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {1 us}
