onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix decimal /tb_bryant_rca_4b/OP_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/OP_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/CLK
add wave -noupdate -radix decimal /tb_bryant_rca_4b/reset
add wave -noupdate -radix decimal /tb_bryant_rca_4b/en
add wave -noupdate -radix decimal /tb_bryant_rca_4b/Sum_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/Exp_Sum_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/Exp_Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/Test_OutS
add wave -noupdate -radix decimal /tb_bryant_rca_4b/LineNumber
add wave -noupdate -radix decimal /tb_bryant_rca_4b/U0/CLK
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/clk
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/reset
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/en
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/s1
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/s2
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/s3
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/s4
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/s5
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/s6
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/Rs1
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/Rs2
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/Rs3
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/Rs4
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/Rs5
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/Rs6
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/c1
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/c2
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/c3
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/c4
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/c5
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/c6
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/RAout1
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/RAout2
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/RAout3
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/RAout4
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/RAout5
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/RAout6
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/RBout1
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/RBout2
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/RBout3
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/RBout4
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/RBout5
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/RBout6
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/Rc1
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/Rc2
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/Rc3
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/Rc4
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/Rc5
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/Rc6
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/s1
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/s2
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/s3
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/s4
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/c1
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/c2
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/c3
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/c4
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/InstBRYANT_First_BSlice1/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/InstBRYANT_First_BSlice1/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/InstBRYANT_First_BSlice1/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/InstBRYANT_First_BSlice1/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/InstBRYANT_GEN_BSlice3/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/InstBRYANT_GEN_BSlice3/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/InstBRYANT_GEN_BSlice3/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/InstBRYANT_GEN_BSlice3/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_First_4B/InstBRYANT_GEN_BSlice3/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG1/clk
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG1/reset
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG1/en
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG1/InA
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG1/InB
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG1/SumIn
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG1/CarryIn
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG1/Aout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG1/Bout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG1/SumOut
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG1/Carryout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG1/sAout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG1/sBout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG1/sSumout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG1/scarryout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/s1
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/s2
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/s3
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/s4
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/c1
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/c2
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/c3
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/c4
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/InstBRYANT_GEN_BSlice3/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/InstBRYANT_GEN_BSlice3/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/InstBRYANT_GEN_BSlice3/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/InstBRYANT_GEN_BSlice3/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/InstBRYANT_GEN_BSlice3/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/InstBRYANT_GEN_BSlice4/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/InstBRYANT_GEN_BSlice4/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/InstBRYANT_GEN_BSlice4/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/InstBRYANT_GEN_BSlice4/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B1/InstBRYANT_GEN_BSlice4/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG2/clk
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG2/reset
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG2/en
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG2/InA
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG2/InB
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG2/SumIn
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG2/PrevSum
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG2/CarryIn
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG2/Aout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG2/Bout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG2/SumOut
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG2/Carryout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG2/sAout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG2/sBout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG2/sSumout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG2/scarryout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/s1
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/s2
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/s3
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/s4
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/c1
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/c2
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/c3
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/c4
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/InstBRYANT_GEN_BSlice3/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/InstBRYANT_GEN_BSlice3/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/InstBRYANT_GEN_BSlice3/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/InstBRYANT_GEN_BSlice3/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/InstBRYANT_GEN_BSlice3/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/InstBRYANT_GEN_BSlice4/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/InstBRYANT_GEN_BSlice4/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/InstBRYANT_GEN_BSlice4/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/InstBRYANT_GEN_BSlice4/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B2/InstBRYANT_GEN_BSlice4/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG3/clk
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG3/reset
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG3/en
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG3/InA
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG3/InB
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG3/SumIn
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG3/PrevSum
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG3/CarryIn
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG3/Aout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG3/Bout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG3/SumOut
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG3/Carryout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG3/sAout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG3/sBout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG3/sSumout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG3/scarryout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/s1
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/s2
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/s3
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/s4
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/c1
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/c2
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/c3
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/c4
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/InstBRYANT_GEN_BSlice3/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/InstBRYANT_GEN_BSlice3/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/InstBRYANT_GEN_BSlice3/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/InstBRYANT_GEN_BSlice3/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/InstBRYANT_GEN_BSlice3/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/InstBRYANT_GEN_BSlice4/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/InstBRYANT_GEN_BSlice4/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/InstBRYANT_GEN_BSlice4/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/InstBRYANT_GEN_BSlice4/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B3/InstBRYANT_GEN_BSlice4/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG4/clk
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG4/reset
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG4/en
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG4/InA
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG4/InB
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG4/SumIn
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG4/PrevSum
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG4/CarryIn
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG4/Aout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG4/Bout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG4/SumOut
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG4/Carryout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG4/sAout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG4/sBout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG4/sSumout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG4/scarryout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/s1
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/s2
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/s3
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/s4
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/c1
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/c2
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/c3
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/c4
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/InstBRYANT_GEN_BSlice3/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/InstBRYANT_GEN_BSlice3/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/InstBRYANT_GEN_BSlice3/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/InstBRYANT_GEN_BSlice3/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/InstBRYANT_GEN_BSlice3/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/InstBRYANT_GEN_BSlice4/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/InstBRYANT_GEN_BSlice4/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/InstBRYANT_GEN_BSlice4/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/InstBRYANT_GEN_BSlice4/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B4/InstBRYANT_GEN_BSlice4/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG5/clk
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG5/reset
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG5/en
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG5/InA
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG5/InB
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG5/SumIn
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG5/PrevSum
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG5/CarryIn
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG5/Aout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG5/Bout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG5/SumOut
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG5/Carryout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG5/sAout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG5/sBout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG5/sSumout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_REG5/scarryout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/s1
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/s2
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/s3
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/s4
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/c1
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/c2
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/c3
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/c4
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/InstBRYANT_GEN_BSlice3/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/InstBRYANT_GEN_BSlice3/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/InstBRYANT_GEN_BSlice3/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/InstBRYANT_GEN_BSlice3/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/InstBRYANT_GEN_BSlice3/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/InstBRYANT_GEN_BSlice4/Op_A
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/InstBRYANT_GEN_BSlice4/Op_B
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/InstBRYANT_GEN_BSlice4/Op_C
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/InstBRYANT_GEN_BSlice4/SUM_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_GEN_4B5/InstBRYANT_GEN_BSlice4/Carry_Q
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_Last_REG1/clk
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_Last_REG1/reset
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_Last_REG1/en
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_Last_REG1/SumIn
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_Last_REG1/PrevSum
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_Last_REG1/CarryIn
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_Last_REG1/SumOut
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_Last_REG1/Carryout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_Last_REG1/sSumout
add wave -noupdate -radix decimal /tb_bryant_rca_4b/InstBRYANT_RCA_4B/InstBRYANT_RCA_Last_REG1/scarryout
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {857 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {1 us}
