onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider Inputs
add wave -noupdate /tb_bryant_rca_2b/CLK
add wave -noupdate /tb_bryant_rca_2b/en
add wave -noupdate /tb_bryant_rca_2b/reset
add wave -noupdate /tb_bryant_rca_2b/OP_A
add wave -noupdate /tb_bryant_rca_2b/OP_B
add wave -noupdate -divider Outputs
add wave -noupdate /tb_bryant_rca_2b/Sum_Q
add wave -noupdate -radix decimal -radixshowbase 0 /tb_bryant_rca_2b/Exp_Sum_Q
add wave -noupdate /tb_bryant_rca_2b/Carry_Q
add wave -noupdate -divider {Test Signals}
add wave -noupdate /tb_bryant_rca_2b/U0/CLK
add wave -noupdate /tb_bryant_rca_2b/LineNumber
add wave -noupdate /tb_bryant_rca_2b/Exp_Carry_Q
add wave -noupdate /tb_bryant_rca_2b/Test_OutS
add wave -noupdate -divider Instantiations
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/clk
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/reset
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/en
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/s1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/s2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/s3
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/s4
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/s5
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/s6
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/s7
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/s8
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/s9
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/s10
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/s11
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/s12
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rs1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rs2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rs3
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rs4
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rs5
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rs6
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rs7
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rs8
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rs9
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rs10
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rs11
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rs12
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/c1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/c2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/c3
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/c4
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/c5
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/c6
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/c7
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/c8
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/c9
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/c10
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/c11
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/c12
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RAout1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RAout2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RAout3
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RAout4
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RAout5
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RAout6
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RAout7
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RAout8
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RAout9
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RAout10
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RAout11
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RAout12
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RBout1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RBout2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RBout3
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RBout4
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RBout5
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RBout6
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RBout7
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RBout8
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RBout9
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RBout10
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RBout11
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/RBout12
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rc1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rc2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rc3
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rc4
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rc5
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rc6
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rc7
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rc8
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rc9
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rc10
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rc11
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/Rc12
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_First_2B/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_First_2B/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_First_2B/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_First_2B/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_First_2B/s1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_First_2B/s2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_First_2B/c1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_First_2B/c2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_First_2B/InstBRYANT_First_BSlice1/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_First_2B/InstBRYANT_First_BSlice1/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_First_2B/InstBRYANT_First_BSlice1/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_First_2B/InstBRYANT_First_BSlice1/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_First_2B/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_First_2B/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_First_2B/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_First_2B/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_First_2B/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG1/clk
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG1/reset
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG1/en
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG1/InA
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG1/InB
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG1/SumIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG1/CarryIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG1/Aout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG1/Bout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG1/SumOut
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG1/Carryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG1/sAout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG1/sBout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG1/sSumout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG1/scarryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B1/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B1/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B1/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B1/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B1/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B1/s1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B1/s2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B1/c1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B1/c2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B1/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B1/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B1/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B1/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B1/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B1/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B1/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B1/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B1/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B1/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG2/clk
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG2/reset
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG2/en
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG2/InA
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG2/InB
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG2/SumIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG2/PrevSum
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG2/CarryIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG2/Aout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG2/Bout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG2/SumOut
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG2/Carryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG2/sAout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG2/sBout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG2/sSumout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG2/scarryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B2/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B2/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B2/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B2/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B2/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B2/s1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B2/s2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B2/c1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B2/c2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B2/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG3/clk
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG3/reset
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG3/en
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG3/InA
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG3/InB
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG3/SumIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG3/PrevSum
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG3/CarryIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG3/Aout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG3/Bout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG3/SumOut
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG3/Carryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG3/sAout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG3/sBout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG3/sSumout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG3/scarryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B3/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B3/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B3/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B3/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B3/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B3/s1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B3/s2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B3/c1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B3/c2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B3/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B3/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B3/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B3/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B3/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B3/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B3/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B3/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B3/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B3/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG4/clk
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG4/reset
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG4/en
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG4/InA
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG4/InB
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG4/SumIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG4/PrevSum
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG4/CarryIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG4/Aout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG4/Bout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG4/SumOut
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG4/Carryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG4/sAout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG4/sBout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG4/sSumout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG4/scarryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B4/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B4/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B4/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B4/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B4/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B4/s1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B4/s2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B4/c1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B4/c2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B4/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B4/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B4/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B4/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B4/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B4/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B4/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B4/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B4/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B4/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG5/clk
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG5/reset
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG5/en
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG5/InA
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG5/InB
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG5/SumIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG5/PrevSum
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG5/CarryIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG5/Aout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG5/Bout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG5/SumOut
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG5/Carryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG5/sAout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG5/sBout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG5/sSumout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG5/scarryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B5/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B5/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B5/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B5/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B5/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B5/s1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B5/s2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B5/c1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B5/c2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B5/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B5/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B5/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B5/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B5/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B5/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B5/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B5/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B5/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B5/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG6/clk
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG6/reset
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG6/en
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG6/InA
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG6/InB
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG6/SumIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG6/PrevSum
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG6/CarryIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG6/Aout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG6/Bout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG6/SumOut
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG6/Carryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG6/sAout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG6/sBout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG6/sSumout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG6/scarryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B6/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B6/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B6/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B6/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B6/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B6/s1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B6/s2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B6/c1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B6/c2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B6/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B6/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B6/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B6/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B6/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B6/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B6/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B6/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B6/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B6/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG7/clk
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG7/reset
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG7/en
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG7/InA
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG7/InB
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG7/SumIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG7/PrevSum
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG7/CarryIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG7/Aout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG7/Bout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG7/SumOut
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG7/Carryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG7/sAout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG7/sBout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG7/sSumout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG7/scarryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B7/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B7/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B7/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B7/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B7/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B7/s1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B7/s2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B7/c1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B7/c2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B7/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B7/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B7/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B7/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B7/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B7/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B7/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B7/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B7/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B7/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG8/clk
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG8/reset
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG8/en
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG8/InA
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG8/InB
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG8/SumIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG8/PrevSum
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG8/CarryIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG8/Aout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG8/Bout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG8/SumOut
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG8/Carryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG8/sAout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG8/sBout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG8/sSumout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG8/scarryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B8/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B8/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B8/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B8/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B8/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B8/s1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B8/s2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B8/c1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B8/c2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B8/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B8/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B8/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B8/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B8/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B8/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B8/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B8/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B8/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B8/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG9/clk
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG9/reset
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG9/en
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG9/InA
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG9/InB
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG9/SumIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG9/PrevSum
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG9/CarryIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG9/Aout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG9/Bout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG9/SumOut
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG9/Carryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG9/sAout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG9/sBout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG9/sSumout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG9/scarryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B9/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B9/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B9/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B9/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B9/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B9/s1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B9/s2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B9/c1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B9/c2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B9/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B9/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B9/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B9/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B9/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B9/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B9/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B9/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B9/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B9/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG10/clk
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG10/reset
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG10/en
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG10/InA
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG10/InB
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG10/SumIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG10/PrevSum
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG10/CarryIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG10/Aout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG10/Bout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG10/SumOut
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG10/Carryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG10/sAout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG10/sBout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG10/sSumout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG10/scarryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B10/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B10/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B10/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B10/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B10/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B10/s1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B10/s2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B10/c1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B10/c2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B10/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B10/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B10/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B10/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B10/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B10/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B10/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B10/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B10/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B10/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG11/clk
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG11/reset
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG11/en
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG11/InA
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG11/InB
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG11/SumIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG11/PrevSum
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG11/CarryIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG11/Aout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG11/Bout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG11/SumOut
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG11/Carryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG11/sAout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG11/sBout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG11/sSumout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_REG11/scarryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B11/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B11/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B11/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B11/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B11/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B11/s1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B11/s2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B11/c1
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B11/c2
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B11/InstBRYANT_GEN_BSlice1/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B11/InstBRYANT_GEN_BSlice1/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B11/InstBRYANT_GEN_BSlice1/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B11/InstBRYANT_GEN_BSlice1/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B11/InstBRYANT_GEN_BSlice1/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B11/InstBRYANT_GEN_BSlice2/Op_A
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B11/InstBRYANT_GEN_BSlice2/Op_B
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B11/InstBRYANT_GEN_BSlice2/Op_C
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B11/InstBRYANT_GEN_BSlice2/SUM_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_GEN_2B11/InstBRYANT_GEN_BSlice2/Carry_Q
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_Last_REG1/clk
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_Last_REG1/reset
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_Last_REG1/en
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_Last_REG1/SumIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_Last_REG1/PrevSum
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_Last_REG1/CarryIn
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_Last_REG1/SumOut
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_Last_REG1/Carryout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_Last_REG1/sSumout
add wave -noupdate /tb_bryant_rca_2b/InstBRYANT_RCA_2B/InstBRYANT_RCA_Last_REG1/scarryout
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0}
quietly wave cursor active 0
configure wave -namecolwidth 305
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {299 ns} {1153 ns}
